create extension if not exists pgcrypto;
create table profiles(id uuid primary key, preferences jsonb not null, created_at timestamptz default now());
create table sources(id uuid primary key default gen_random_uuid(), company text not null, careers_url text not null, source_type text not null, parser_config jsonb, active boolean default true);
create table jobs(id uuid primary key default gen_random_uuid(), source_id uuid references sources(id), external_id text, canonical_url text not null, title text not null, company text not null, locations jsonb, description_text text, employment_type text, posted_at timestamptz, first_seen_at timestamptz default now(), last_seen_at timestamptz default now(), status text default 'active', content_hash text, unique(source_id,external_id));
create table job_requirements(job_id uuid primary key references jobs(id) on delete cascade, years_min numeric, years_max numeric, education jsonb, skills jsonb, security_clearance text, travel text, extracted_evidence jsonb, confidence numeric);
create table verifications(id bigserial primary key, job_id uuid references jobs(id), checked_at timestamptz default now(), http_status int, final_url text, active_signal text, evidence jsonb);
create table matches(id uuid primary key default gen_random_uuid(), profile_id uuid references profiles(id), job_id uuid references jobs(id), score int, hard_filter_result jsonb, matched jsonb, missing jsonb, uncertain jsonb, model_version text, created_at timestamptz default now(), unique(profile_id,job_id));
create table saved_jobs(id uuid primary key default gen_random_uuid(), profile_id uuid references profiles(id), job_id uuid references jobs(id), stage text default 'saved', resume_version text, notes text, created_at timestamptz default now());
create table notifications(id uuid primary key default gen_random_uuid(), profile_id uuid references profiles(id), job_id uuid references jobs(id), reason text, channel text, sent_at timestamptz, dedupe_key text unique);
