import type { Job } from "./types";

export const jobs: Job[] = [
  {
    id: "j1",
    title: "Product Cybersecurity Engineer",
    company: "Example Mobility",
    location: "Dearborn, MI",
    posted: "2 days ago",
    years: "0–3",
    status: "verified",
    score: 91,
    officialUrl: "https://example.com/careers/j1",
    matched: ["Automotive security", "Python", "ISO/SAE 21434 familiarity"],
    missing: ["Production TARA ownership"],
    evidence: "“0–3 years of experience in embedded or product security.” — retrieved from official posting",
  },
  {
    id: "j2",
    title: "Embedded Software Validation Engineer",
    company: "Example Automotive",
    location: "Warren, MI",
    posted: "Today",
    years: "2–5",
    status: "verified",
    score: 84,
    officialUrl: "https://example.com/careers/j2",
    matched: ["C++", "CAN / OBD-II", "Test fundamentals"],
    missing: ["CAPL"],
    evidence: "“2–5 years working with vehicle communication protocols.” — retrieved from official posting",
  },
  {
    id: "j3",
    title: "Cyber Defense Analyst",
    company: "Example Enterprise",
    location: "Detroit, MI",
    posted: "5 days ago",
    years: "1–3",
    status: "uncertain",
    score: 76,
    officialUrl: "https://example.com/careers/j3",
    matched: ["SOC labs", "Wireshark", "Splunk"],
    missing: ["24/7 shift availability not confirmed"],
    evidence: "Active-status signal ambiguous on last re-check — held from digest until confirmed",
  },
  {
    id: "j4",
    title: "Firmware Engineer, Battery Systems",
    company: "Example Energy",
    location: "Novi, MI",
    posted: "1 day ago",
    years: "1–4",
    status: "verified",
    score: 79,
    officialUrl: "https://example.com/careers/j4",
    matched: ["Embedded C", "RTOS", "Battery management systems"],
    missing: ["ASPICE process exposure"],
    evidence: "“1–4 years of embedded firmware experience.” — retrieved from official posting",
  },
  {
    id: "j5",
    title: "Automotive Penetration Tester",
    company: "Example Labs",
    location: "Ann Arbor, MI",
    posted: "6 days ago",
    years: "3–6",
    status: "closed",
    score: 68,
    officialUrl: "https://example.com/careers/j5",
    matched: ["Hardware hacking", "CAN fuzzing", "Reverse engineering"],
    missing: ["Requires 3+ yrs — above early-career target"],
    evidence: "Posting returned removed/closed on last re-check — flagged as a correction, not sent",
  },
];
